"""initial_schema

Revision ID: c957d12130b9
Revises: 
Create Date: 2026-05-18 16:32:52.539028

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c957d12130b9'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clients',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=True),
    sa.Column('company_name', sa.String(length=255), nullable=False),
    sa.Column('s3_bucket', sa.String(length=255), nullable=True),
    sa.Column('s3_prefix', sa.String(length=255), nullable=True),
    sa.Column('log_format', sa.String(length=50), nullable=True),
    sa.Column('aws_region', sa.String(length=50), nullable=True),
    sa.Column('last_processed_key', sa.Text(), nullable=True),
    sa.Column('waf_ip_set_id', sa.String(length=255), nullable=True),
    sa.Column('cloudflare_zone_id', sa.String(length=255), nullable=True),
    sa.Column('cloudflare_token', sa.Text(), nullable=True),
    sa.Column('alert_email', sa.String(length=255), nullable=True),
    sa.Column('tier', sa.String(length=20), nullable=False),
    sa.Column('email_verified', sa.Boolean(), nullable=False),
    sa.Column('mfa_enabled', sa.Boolean(), nullable=False),
    sa.Column('mfa_secret', sa.Text(), nullable=True),
    sa.Column('verify_token', sa.Text(), nullable=True),
    sa.Column('verify_token_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reset_token_hash', sa.Text(), nullable=True),
    sa.Column('reset_token_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clients_email'), 'clients', ['email'], unique=True)
    op.create_table('ip_memory',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('client_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('ip', sa.String(length=45), nullable=False),
    sa.Column('first_seen', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen', sa.DateTime(timezone=True), nullable=False),
    sa.Column('total_requests', sa.Integer(), nullable=False),
    sa.Column('threat_count', sa.Integer(), nullable=False),
    sa.Column('risk_score', sa.Float(), nullable=False),
    sa.Column('geo_country', sa.String(length=10), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('client_id', 'ip', name='uq_ip_memory_client_ip')
    )
    op.create_index(op.f('ix_ip_memory_client_id'), 'ip_memory', ['client_id'], unique=False)
    op.create_index(op.f('ix_ip_memory_ip'), 'ip_memory', ['ip'], unique=False)
    op.create_table('oauth_accounts',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('client_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('provider_id', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'provider_id', name='uq_oauth_provider_id')
    )
    op.create_index(op.f('ix_oauth_accounts_client_id'), 'oauth_accounts', ['client_id'], unique=False)
    op.create_table('refresh_tokens',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('client_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('token_hash', sa.Text(), nullable=False),
    sa.Column('issued_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked', sa.Boolean(), nullable=False),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('ip', sa.String(length=45), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_index(op.f('ix_refresh_tokens_client_id'), 'refresh_tokens', ['client_id'], unique=False)
    op.create_table('verdicts',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('client_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ip', sa.String(length=45), nullable=False),
    sa.Column('method', sa.String(length=10), nullable=True),
    sa.Column('endpoint', sa.Text(), nullable=True),
    sa.Column('threat_type', sa.String(length=100), nullable=True),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('agents_triggered', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.Column('blocked', sa.Boolean(), nullable=False),
    sa.Column('cost_prevented', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_verdicts_client_id'), 'verdicts', ['client_id'], unique=False)
    op.create_index(op.f('ix_verdicts_ip'), 'verdicts', ['ip'], unique=False)
    op.create_index(op.f('ix_verdicts_timestamp'), 'verdicts', ['timestamp'], unique=False)
    op.create_table('alerts_sent',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('client_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('verdict_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('channel', sa.String(length=50), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['verdict_id'], ['verdicts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alerts_sent_client_id'), 'alerts_sent', ['client_id'], unique=False)
    op.create_index(op.f('ix_alerts_sent_verdict_id'), 'alerts_sent', ['verdict_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_alerts_sent_verdict_id'), table_name='alerts_sent')
    op.drop_index(op.f('ix_alerts_sent_client_id'), table_name='alerts_sent')
    op.drop_table('alerts_sent')
    op.drop_index(op.f('ix_verdicts_timestamp'), table_name='verdicts')
    op.drop_index(op.f('ix_verdicts_ip'), table_name='verdicts')
    op.drop_index(op.f('ix_verdicts_client_id'), table_name='verdicts')
    op.drop_table('verdicts')
    op.drop_index(op.f('ix_refresh_tokens_client_id'), table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_index(op.f('ix_oauth_accounts_client_id'), table_name='oauth_accounts')
    op.drop_table('oauth_accounts')
    op.drop_index(op.f('ix_ip_memory_ip'), table_name='ip_memory')
    op.drop_index(op.f('ix_ip_memory_client_id'), table_name='ip_memory')
    op.drop_table('ip_memory')
    op.drop_index(op.f('ix_clients_email'), table_name='clients')
    op.drop_table('clients')
    # ### end Alembic commands ###
